# Representation of a single track.

builtin_interfaces/Time stamp   # time stamp of track determined
float32 position_y              # center y position (m)
float32 position_x              # center x position (m)
float32 velocity_y              # y velocity (m/s)
float32 velocity_x              # x velocity (m/s)
float32 width                   # width of object (along y) (m)
float32 length                  # length of object (along x) (m)
float32 height                  # height of object (m)
